# Base URL
baseurl: ""

# Site live URL
url: https://test.egilh.no

# Localhost
# url: http://127.0.0.1:4000

# Harmony theme configuration. Please change accordingly.
harmony:
  name: egil.ninja
  # Little description about your site
  description: DevOps Engineering
  avatar: https://avatars1.githubusercontent.com/u/5278037?v=3&u=be38ce94b0d6d0d249ae99bfae9cad2aa3c7be12&s=140
    # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and
  # in your feed.xml site description.
  meta_description: > #
    Everything DevOps related from my daily work and private projects.

  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Egil Haugli
    email: egilrs@gmail.com
    url: http://egilh.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key:

  # Profile links, leave blank to ignore
  social:
    github: egilh
    twitter:
    facebook: egilh
    gplus: +egilh
    linkedin: egilhaugli
    flickr: egilh
    instagram: egilhaugli
  # Toggle disclaimer in footer
  show_disclaimer: true

# Conversion / Build settings
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

# Permalinks
permalink:        pretty
paginate_path: /page:num
timezone:      Europe/Oslo

quiet:    false
defaults: []

# Handling Reading
safe:         true
include:      [".htaccess"]
exclude:
  - CNAME
  - Gemfile
  - LICENSE
  - README.md
  - vendor
  - .gitignore
  - .sass-cache
  - Gemfile.lock
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Markdown Processors
maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
